before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: dGv1OLM+8A7uPb4rUb+H/ELW9lT6oQIotBUPjwqL87X3R1895G+2AyO0xEH7KEjykt1w1x/FjN4eLTtx/zHCmeyYTe8jY+Znjfx/++qN36E1g9A3kFZFdJK5ZAaeIsKM8kumPnYEW72hci3R6b8I5NsdvvyhaWjW4Mtc2dlK2NSCqsovYA1GJsl/jYgCgCgOcloTdmMQ1WQwlwRG5+0+k7q+mq3b/hmfJhvfxWhNp4cShXYoEMwQ3Z8JfIRqzsoWFLKDGrxvJevY12NKYGptYOs6CQ7sSquqSwCYvVmjfmArKpEA3jYJVQZItzvKtGsKAyWKjLuvJJLTa3e6WLl6bFdKYilA/xzDOQvRPcAvM3uHBeZW+MyTiUKsWYgdeNrGD1+s1sQAO0vfrtB43fneDBYatuf4+AQTm2JchRe5EwYdJaTR8rL/szGWlG398ccJhinF62iEU1o7INAGzZ5JcLQ4fPdmlama0YKVRoTEJDUSEV/P2I1dFwpXrirqLqtqQDW9t2QmzaLbwhdX4+jNzS+KMzWx1mcIgZBLvTg/57J9q7TOkUawM7hETnk9c+9PQ3tEksNIkX1RDZnxipVk8MAoQkDOFG+gVZYrEoSnPyyJB7aaP+DG7E5qEpkSBuOYlCTx+UoDT/7ivdZIY3Z0X7oC+pgB7a3hb2goC/bsWVI= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
